node {
  name = "emqx@127.0.0.1"
  cookie = "IoTeca-emqx-cookie"
  data_dir = "/var/lib/emqx"
}

cluster {
  name = IoTeca
  discovery_strategy = manual
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 100000
}

listeners.ws.default {
  bind = "0.0.0.0:8083"
}

authentication = [
  {
    mechanism = password_based
    backend = http
    method = post
    url = "http://auth-service:8081/api/internal/emqx/auth"
    headers { "Content-Type" = "application/json" }
    body {
      username = "${username}"
      password = "${password}"
      clientid = "${clientid}"
    }
  }
]

authorization {
  no_match = deny
  deny_action = disconnect
  sources = [
    {
      type = http
      enable = true
      method = post
      url = "http://auth-service:8081/api/internal/emqx/acl"
      headers { "Content-Type" = "application/json" }
      body {
        username = "${username}"
        topic = "${topic}"
        action = "${action}"
      }
    }
  ]
}

bridges.webhook.ioteca_ingest {
  enable = true
  url = "http://api-gateway:8080/api/v1/ingest/mqtt"
  method = post
  headers {
    "content-type" = "application/json"
    "x-emqx-secret" = "${EMQX_INTERNAL_SECRET}"
  }
  body = "${.}"
}

rule_engine {
  rules {
    device_mqtt_ingest {
      enable = true
      sql = "SELECT username as project_id, json_decode(payload) as payload FROM \"ioteca/#\""
      actions = ["webhook:ioteca_ingest"]
    }
  }
}

