broker.id=1
listeners=PLAINTEXT://0.0.0.0:9092
advertised.listeners=PLAINTEXT://kafka:9092
log.dirs=/var/lib/kafka/data
num.partitions=3
default.replication.factor=1
log.retention.hours=168
log.retention.bytes=-1
log.segment.bytes=1073741824
zookeeper.connect=zookeeper:2181
auto.create.topics.enable=false
